server:
  error:
    include-stacktrace: NEVER
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/locadora?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    url: jdbc:postgresql://localhost:5432/locadora
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.PostgreSQL95Dialect

#spring.datasource.url=jdbc:mysql://localhost:3306/locadora?useTimezone=true&serverTimezone=UTC
##spring.jpa.database-platform=org.hibernate.dialect.MySQLInnoDBDialect
##spring.jpa.database-platform=org.hibernate.dialect.MySQLMyISAMDialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL55Dialect
##hibernate.dialect=org.hibernate.dialect.MySQLInnoDBDialect
##hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driverClassName=com.mysql.jdbc.Driver
#spring.datasource.username=rick
#spring.datasource.password=Locador@1
